/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.32                          *
 *        Compiled Oct  8 2015, 11:59:02                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
// USER END
#include "DIALOG.h"
#include "stdint.h"
#include "Layout_Config.h"
#include "GUIControl.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x01)		// SollTemperatur
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x02)		// Raumtemperatur
#define ID_CHECKBOX_2 (GUI_ID_USER + 0x03)		// Aussentemperatur
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x04)		// Luftstrom 1
#define ID_CHECKBOX_4 (GUI_ID_USER + 0x05)		// Ausseneinheit 1
#define ID_CHECKBOX_5 (GUI_ID_USER + 0x06)		// Luftstrom 2
#define ID_CHECKBOX_6 (GUI_ID_USER + 0x07)		// Ausseneinheit 2
#define ID_CHECKBOX_7 (GUI_ID_USER + 0x08)		// Motortemperatur
#define ID_CHECKBOX_8 (GUI_ID_USER + 0x09)		// Temperatur CAN
#define ID_BUTTON_0 (GUI_ID_USER + 0x0A)		// Fenster schließen

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
extern GUI_COLOR _aColor[];
extern uint8_t enableLine[9];
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogGraphLinesCreate[] = {
		{ FRAMEWIN_CreateIndirect, "Anzeige", 			ID_FRAMEWIN_0, 	90, 	56, 300, 160, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Solltemperatur", 	ID_CHECKBOX_0, 	10, 	10, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Raumtemperatur", 	ID_CHECKBOX_1, 	160, 	10, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Aussentemepratur", 	ID_CHECKBOX_2, 	10, 	35, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Luftstrom 1", 		ID_CHECKBOX_3, 	160, 	35, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Ausseneinheit 1", 	ID_CHECKBOX_4, 	10, 	60, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Luftstrom 2", 		ID_CHECKBOX_5, 	160, 	60, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Ausseneinheit 2", 	ID_CHECKBOX_6, 	10, 	85, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Motortemperatur", 	ID_CHECKBOX_7, 	160, 	85, 140, 20, 0, 0x0, 0 },
		{ CHECKBOX_CreateIndirect, "Temperatur CAN", 	ID_CHECKBOX_8, 	10, 	110, 140, 20, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "Schließen", 			ID_BUTTON_0, 	204, 	109, 80, 25, 0, 0x0, 0 },
// USER START (Optionally insert additional widgets)
// USER END
		};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END
/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialogGraphLines(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int NCode;
	int Id;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Solltemperatur'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetTextColor(hItem, _aColor[0]);
		CHECKBOX_SetText(hItem, "Solltemperatur");
		CHECKBOX_SetState(hItem, enableLine[0]);
		//
		// Initialization of 'Raumtemperatur'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetTextColor(hItem, _aColor[1]);
		CHECKBOX_SetText(hItem, "Raumtemperatur");
		CHECKBOX_SetState(hItem, enableLine[1]);
		//
		// Initialization of 'Aussentemperatur'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
		CHECKBOX_SetTextColor(hItem, _aColor[2]);
		CHECKBOX_SetText(hItem, "Aussentemperatur");
		CHECKBOX_SetState(hItem, enableLine[2]);
		//
		// Initialization of 'Luftstrom 1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
		CHECKBOX_SetTextColor(hItem, _aColor[3]);
		CHECKBOX_SetText(hItem, "Luftstrom 1");
		CHECKBOX_SetState(hItem, enableLine[3]);
		//
		// Initialization of 'Ausseneinheit 1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
		CHECKBOX_SetTextColor(hItem, _aColor[4]);
		CHECKBOX_SetText(hItem, "Ausseneinheit 1");
		CHECKBOX_SetState(hItem, enableLine[4]);
		//
		// Initialization of 'Luftstrom 2'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
		CHECKBOX_SetTextColor(hItem, _aColor[5]);
		CHECKBOX_SetText(hItem, "Luftstrom 2");
		CHECKBOX_SetState(hItem, enableLine[5]);
		//
		// Initialization of 'Ausseneinheit 2'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
		CHECKBOX_SetTextColor(hItem, _aColor[6]);
		CHECKBOX_SetText(hItem, "Ausseneinheit 2");
		CHECKBOX_SetState(hItem, enableLine[6]);
		//
		// Initialization of 'Motortemperatur'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
		CHECKBOX_SetTextColor(hItem, _aColor[7]);
		CHECKBOX_SetText(hItem, "Motortemperatur");
		CHECKBOX_SetState(hItem, enableLine[7]);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8);
		CHECKBOX_SetTextColor(hItem, _aColor[8]);
		CHECKBOX_SetText(hItem, "Temperatur CAN");
		CHECKBOX_SetState(hItem, enableLine[8]);

		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_CHECKBOX_0: // Notifications sent by 'Raumtemperatur'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_1: // Notifications sent by 'Aussentemperatur'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_2: // Notifications sent by 'Luftstrom 1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_3: // Notifications sent by 'Luftstrom 2'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_4: // Notifications sent by 'Motortemperatur'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_5: // Notifications sent by 'Ausseneinheit 2'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_6: // Notifications sent by 'Ausseneinheit 1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_CHECKBOX_7: // Notifications sent by 'Öltemperatur'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_0: // Notifications sent by 'Schließen'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:

				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
				enableLine[0] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
				enableLine[1] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
				enableLine[2] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
				enableLine[3] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
				enableLine[4] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
				enableLine[5] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
				enableLine[6] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
				enableLine[7] = CHECKBOX_GetState(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8);
				enableLine[8] = CHECKBOX_GetState(hItem);

				uint16_t GraphEnable = 	 enableLine[0] |
										(enableLine[1] << 1) |
										(enableLine[2] << 2) |
										(enableLine[3] << 3) |
										(enableLine[4] << 4) |
										(enableLine[5] << 5) |
										(enableLine[6] << 6) |
										(enableLine[7] << 7) |
										(enableLine[8] << 8);

				ParameterWrite((&GraphDispLines),Value, GraphEnable);
				ParameterChange_Handled = 0;

				GUI_EndDialog(pMsg->hWin, 0);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateAnzeige
 */
WM_HWIN CreateAnzeige(void);
WM_HWIN CreateAnzeige(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogGraphLinesCreate, GUI_COUNTOF(_aDialogGraphLinesCreate),
			_cbDialogGraphLines, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
