/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Main                                                  *
* Dimensions:  68 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"
#include "Layout_CONFIG.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmMain;

static GUI_CONST_STORAGE GUI_COLOR _ColorsMain[] = {
      0xFFFFFF, IAV_BLAU_3
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalMain = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsDataType[0]
};

static GUI_CONST_STORAGE unsigned char _acMain[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, XXXX____, __XXXXX_, ________, ________, ________, ________,
  ________, ________, ________, XXXX___X, XXXXXXXX, X_______, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmMain = {
  68, // xSize
  40, // ySize
  9, // BytesPerLine
  1, // BitsPerPixel
  _acMain,  // Pointer to picture data (indices)
  &_PalMain   // Pointer to palette
};

/*************************** End of file ****************************/
