/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Fliekomma                                             *
* Dimensions:  40 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmFliekomma;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsFliekomma[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalFliekomma = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsFliekomma[0]
};

static GUI_CONST_STORAGE unsigned char _acFliekomma[] = {
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, __XXXXXX, XXX_____, ________,
  ______X_, ________, ______XX, XXX_____, ________,
  ______X_, ________, ______XX, XXX_____, ________,
  ______X_, ________, ______XX, XX______, ________,
  ______X_, ________, ______XX, XX______, ________,
  ______X_, ________, _____XXX, XX______, ________,
  ______X_, ________, ____XXXX, X_______, ________,
  ______X_, ________, __XXXXXX, X_______, ________,
  ______X_, ________, _XXXXXXX, ________, ________,
  ______X_, ________, __XXXXX_, ________, ________,
  ______X_, ________, __XXX___, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______X_, ________, ________, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmFliekomma = {
  40, // xSize
  40, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acFliekomma,  // Pointer to picture data (indices)
  &_PalFliekomma   // Pointer to palette
};

/*************************** End of file ****************************/
