/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Bild3                                                 *
* Dimensions:  67 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"
#include "Layout_CONFIG.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmBild3;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalBild3 = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsDataType[0]
};

static GUI_CONST_STORAGE unsigned char _acBild3[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XX__XXXX, __XXXXXX, XXXXXXXX, XX__XXX_, XX__XXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XX_XXXXX, X_XXXXXX, XXXXXXXX, XX__XX__, XX__XXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XX_XXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XX_XXXXX, X_XXXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XXXXXXXX, XX_XXXXX, X_XXXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XXXXXXXX, XX_XXXXX, X_XXXXXX, XXXXX__X, ________, _______X, __XXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXX_XX, ________, _______X, _XXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XX_X_X__, X_X_X__X, X_XXXXXX, XXXXX__X, ________, _______X, __XXX___, __X_____,
  X______X, XX_X_XX_, X_X_XX_X, X_XXXXXX, XXXXX_XX, ________, _______X, _XXXX___, __X_____,
  X______X, XX_X_XX_, X_X_XX_X, X_XXXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XX_X_XX_, X_X_XX_X, X_XXXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXX__X, ________, _______X, __XXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXX_XX, ________, _______X, _XXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, ________, _______X, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XX_XXXXX, XXXX__XX, ________, _______X, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XX__XXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XXX___XX, X___XXXX, XXX_XXX_, XXX_XXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX, XX__XX__, XX__XXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, ________, ________, ________, __X_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmBild3 = {
  67, // xSize
  40, // ySize
  9, // BytesPerLine
  1, // BitsPerPixel
  _acBild3,  // Pointer to picture data (indices)
  &_PalBild3   // Pointer to palette
};

/*************************** End of file ****************************/
