/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DataType_P                                            *
* Dimensions:  39 * 62                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmDataType_P;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsDataType_P[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalDataType_P = {
  2,  // Number of entries
  0,  // No transparency
  &_ColorsDataType_P[0]
};

static GUI_CONST_STORAGE unsigned char _acDataType_P[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, _______X, X_______, ____XXX_,
  XXX_____, ____XXX_, ______XX, XX______, ____XXX_,
  XXX_____, ___XXXXX, X____XXX, XXX_____, ____XXX_,
  XXX_____, __XXXXXX, X___XXXX, XXXX____, ____XXX_,
  XXX_____, __XXXXXX, XX_XXXXX, XXXXX___, ____XXX_,
  XXX_____, __XXXXXX, XXXXXXXX, XXXXXX__, ____XXX_,
  XXX_____, __XXXXXX, XXXXXXXX, XXXXX___, ____XXX_,
  XXX_____, __XXXXXX, XXXXXXXX, XXXX____, ____XXX_,
  XXX_____, ___XXXXX, XXXXXXXX, XXX_____, ____XXX_,
  XXX_____, ______XX, XXXXXXXX, XX______, ____XXX_,
  XXX_____, _____XXX, XXXXXXXX, X_______, ____XXX_,
  XXX_____, ____XXXX, XXXXXXXX, ________, ____XXX_,
  XXX_____, ___XXXXX, XXXXXXXX, XX______, ____XXX_,
  XXX_____, __XXXXXX, XXXXXXXX, XXXX____, ____XXX_,
  XXX_____, _XXXXXXX, XXXXXXXX, XXXX____, ____XXX_,
  XXX_____, _XXXXXXX, XXXX_XXX, XXXXX___, ____XXX_,
  XXX_____, _XXXXXXX, XXX__XXX, XXXXX___, ____XXX_,
  XXX_____, __XXXXXX, XX___XXX, XXXX____, ____XXX_,
  XXX_____, ___XXXXX, X____XXX, XXXX____, ____XXX_,
  XXX_____, ____XXXX, ______XX, XXX_____, ____XXX_,
  XXX_____, _____XX_, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXX_____, ________, ________, ________, ____XXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmDataType_P = {
  39, // xSize
  62, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _acDataType_P,  // Pointer to picture data (indices)
  &_PalDataType_P   // Pointer to palette
};

/*************************** End of file ****************************/
